// Code generated by ent, DO NOT EDIT.

package route

const (
	// Label holds the string label denoting the route type in the database.
	Label = "route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "route_id"
	// FieldRouteName holds the string denoting the route_name field in the database.
	FieldRouteName = "route_name"
	// FieldLoad holds the string denoting the load field in the database.
	FieldLoad = "load"
	// FieldCargoType holds the string denoting the cargo_type field in the database.
	FieldCargoType = "cargo_type"
	// FieldIsActual holds the string denoting the is_actual field in the database.
	FieldIsActual = "is_actual"
	// Table holds the table name of the route in the database.
	Table = "routes"
)

// Columns holds all SQL columns for route fields.
var Columns = []string{
	FieldID,
	FieldRouteName,
	FieldLoad,
	FieldCargoType,
	FieldIsActual,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsActual holds the default value on creation for the "is_actual" field.
	DefaultIsActual bool
)
