// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"helloworld/internal/data/ent/predicate"
	"helloworld/internal/data/ent/route"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RouteUpdate is the builder for updating Route entities.
type RouteUpdate struct {
	config
	hooks    []Hook
	mutation *RouteMutation
}

// Where appends a list predicates to the RouteUpdate builder.
func (ru *RouteUpdate) Where(ps ...predicate.Route) *RouteUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetRouteName sets the "route_name" field.
func (ru *RouteUpdate) SetRouteName(s string) *RouteUpdate {
	ru.mutation.SetRouteName(s)
	return ru
}

// SetLoad sets the "load" field.
func (ru *RouteUpdate) SetLoad(f float64) *RouteUpdate {
	ru.mutation.ResetLoad()
	ru.mutation.SetLoad(f)
	return ru
}

// AddLoad adds f to the "load" field.
func (ru *RouteUpdate) AddLoad(f float64) *RouteUpdate {
	ru.mutation.AddLoad(f)
	return ru
}

// SetCargoType sets the "cargo_type" field.
func (ru *RouteUpdate) SetCargoType(s string) *RouteUpdate {
	ru.mutation.SetCargoType(s)
	return ru
}

// SetIsActual sets the "is_actual" field.
func (ru *RouteUpdate) SetIsActual(b bool) *RouteUpdate {
	ru.mutation.SetIsActual(b)
	return ru
}

// SetNillableIsActual sets the "is_actual" field if the given value is not nil.
func (ru *RouteUpdate) SetNillableIsActual(b *bool) *RouteUpdate {
	if b != nil {
		ru.SetIsActual(*b)
	}
	return ru
}

// Mutation returns the RouteMutation object of the builder.
func (ru *RouteUpdate) Mutation() *RouteMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RouteUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RouteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			if ru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RouteUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RouteUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RouteUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RouteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   route.Table,
			Columns: route.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: route.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RouteName(); ok {
		_spec.SetField(route.FieldRouteName, field.TypeString, value)
	}
	if value, ok := ru.mutation.Load(); ok {
		_spec.SetField(route.FieldLoad, field.TypeFloat64, value)
	}
	if value, ok := ru.mutation.AddedLoad(); ok {
		_spec.AddField(route.FieldLoad, field.TypeFloat64, value)
	}
	if value, ok := ru.mutation.CargoType(); ok {
		_spec.SetField(route.FieldCargoType, field.TypeString, value)
	}
	if value, ok := ru.mutation.IsActual(); ok {
		_spec.SetField(route.FieldIsActual, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// RouteUpdateOne is the builder for updating a single Route entity.
type RouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RouteMutation
}

// SetRouteName sets the "route_name" field.
func (ruo *RouteUpdateOne) SetRouteName(s string) *RouteUpdateOne {
	ruo.mutation.SetRouteName(s)
	return ruo
}

// SetLoad sets the "load" field.
func (ruo *RouteUpdateOne) SetLoad(f float64) *RouteUpdateOne {
	ruo.mutation.ResetLoad()
	ruo.mutation.SetLoad(f)
	return ruo
}

// AddLoad adds f to the "load" field.
func (ruo *RouteUpdateOne) AddLoad(f float64) *RouteUpdateOne {
	ruo.mutation.AddLoad(f)
	return ruo
}

// SetCargoType sets the "cargo_type" field.
func (ruo *RouteUpdateOne) SetCargoType(s string) *RouteUpdateOne {
	ruo.mutation.SetCargoType(s)
	return ruo
}

// SetIsActual sets the "is_actual" field.
func (ruo *RouteUpdateOne) SetIsActual(b bool) *RouteUpdateOne {
	ruo.mutation.SetIsActual(b)
	return ruo
}

// SetNillableIsActual sets the "is_actual" field if the given value is not nil.
func (ruo *RouteUpdateOne) SetNillableIsActual(b *bool) *RouteUpdateOne {
	if b != nil {
		ruo.SetIsActual(*b)
	}
	return ruo
}

// Mutation returns the RouteMutation object of the builder.
func (ruo *RouteUpdateOne) Mutation() *RouteMutation {
	return ruo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RouteUpdateOne) Select(field string, fields ...string) *RouteUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Route entity.
func (ruo *RouteUpdateOne) Save(ctx context.Context) (*Route, error) {
	var (
		err  error
		node *Route
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RouteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			if ruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Route)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RouteMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RouteUpdateOne) SaveX(ctx context.Context) *Route {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RouteUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RouteUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RouteUpdateOne) sqlSave(ctx context.Context) (_node *Route, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   route.Table,
			Columns: route.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: route.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Route.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, route.FieldID)
		for _, f := range fields {
			if !route.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != route.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.RouteName(); ok {
		_spec.SetField(route.FieldRouteName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Load(); ok {
		_spec.SetField(route.FieldLoad, field.TypeFloat64, value)
	}
	if value, ok := ruo.mutation.AddedLoad(); ok {
		_spec.AddField(route.FieldLoad, field.TypeFloat64, value)
	}
	if value, ok := ruo.mutation.CargoType(); ok {
		_spec.SetField(route.FieldCargoType, field.TypeString, value)
	}
	if value, ok := ruo.mutation.IsActual(); ok {
		_spec.SetField(route.FieldIsActual, field.TypeBool, value)
	}
	_node = &Route{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
