// Code generated by ent, DO NOT EDIT.

package ent

import (
	"helloworld/internal/data/ent/route"
	"helloworld/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescIsActual is the schema descriptor for is_actual field.
	routeDescIsActual := routeFields[4].Descriptor()
	// route.DefaultIsActual holds the default value on creation for the is_actual field.
	route.DefaultIsActual = routeDescIsActual.Default.(bool)
}
