server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  relational:
    dialect: postgres
    host: localhost
    port: 5432
    user: keycloak
    password: keycloak
    dbname: keycloak
    ssl_mode: disable
#  redis:
#    addr: 127.0.0.1:6379
#    read_timeout: 0.2s
#    write_timeout: 0.2s
