server:
  http:
    addr: 0.0.0.0:8080
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9080
    timeout: 3s
data:
  room_availability:
    - hotel_id: redisson
      room_id: lux
      date: 2024-01-01
      quota: 1
    - hotel_id: redisson
      room_id: lux
      date: 2024-01-02
      quota: 1
    - hotel_id: redisson
      room_id: lux
      date: 2024-01-03
      quota: 1
    - hotel_id: redisson
      room_id: lux
      date: 2024-01-04
      quota: 1
    - hotel_id: redisson
      room_id: lux
      date: 2024-01-05
      quota: 0
