// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RoutesColumns holds the columns for the "routes" table.
	RoutesColumns = []*schema.Column{
		{Name: "route_id", Type: field.TypeUint64, Increment: true},
		{Name: "route_name", Type: field.TypeString},
		{Name: "load", Type: field.TypeFloat64},
		{Name: "cargo_type", Type: field.TypeString},
		{Name: "is_actual", Type: field.TypeBool, Default: false},
	}
	// RoutesTable holds the schema information for the "routes" table.
	RoutesTable = &schema.Table{
		Name:       "routes",
		Columns:    RoutesColumns,
		PrimaryKey: []*schema.Column{RoutesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RoutesTable,
	}
)

func init() {
}
